### ISSUE TITLE
Is this project still mantained?

### ISSUE THREAD

**Issue by sotojuan** [alco/chatty#21]
Not much activity since last year (eight months now). I was hoping to build something similar to Alhi with this, but was wondering what the support status on this is.

**Comment by alco** [comment]
@sotojuan Hi. I appreciate your interest in this library. Though I haven't been working on it for a while, I'm generally available for questions should you have any.

**Comment by sotojuan** [comment]
Thanks!

**Comment by sotojuan** [comment]
Oh and is there a reason this isn't on Hex?

**Comment by alco** [comment]
@sotojuan It is now.
