### ISSUE TITLE
Adding listener to private message

### ISSUE THREAD

**Issue by MrDunne** [alco/chatty#4]
Maybe I'm just derping, but I'm currently trying to work out how to listen to private messages.

Currently have listening working on public channels.

    Chatty.add_hook :MainHook, &MainHook.run/2, in: :text, channel: "testing-ba"
    Chatty.add_hook :ping, &PingHook.run/2, in: :text, direct: true
    Chatty.add_hook :replytwo, &MainHook.run/2, in: :text    
    Chatty.add_hook :reply, &MainHook.run/2, in: :text, direct: true

This is what I'm trying so far, the first and second work.

I'm sure I'm missing something obvious here.

**Comment by alco** [comment]
Hi. Chatty didn't use to handle replies from hooks for private messages properly. I have fixed this on [master](https://github.com/alco/chatty/tree/b63228e285427877e863fc3902f7fe422addd8f9).

By default hooks are only enabled on public channels. To also enable them in private conversations, include `public_only: false` in the list of options, e.g.

```elixir
Chatty.add_hook :ping, &Chatty.Hooks.PingHook.run/2, public_only: false
```

**Comment by MrDunne** [comment]
Oh wow, thanks. Quick fix!
