### ISSUE TITLE
MatchError on channel messages

### ISSUE THREAD

**Issue by Annwenn** [alco/chatty#6]
Hi,
I'm facing this kind of error for a while now, and I was wondering what could be its cause.
```Elixir
[chatty] :Uniaika!~xxx@xxxxxxx PRIVMSG #FoobarLol :foobarlol
[chatty] %MatchError{term: "foobarlol"}
```

**Comment by alco** [comment]
There is a single place where errors are caught and logged, [here](https://github.com/alco/chatty/blob/61f08631c133733e9e2f98a5c5fa37c2fd5b6eda/lib/chatty/conn_server.ex#L157-L161).

The error comes either from `HookHelpers` or from a custom hook you have installed. You can try removing the `try` block to get a trace when the error happens next time.

**Comment by Annwenn** [comment]
I shall do that ;) thank you!

**Comment by alco** [comment]
@Annwenn did you find out what the error was?

**Comment by Annwenn** [comment]
@alco I'd bet on an implementation error  from Queertoo Dev Team's side. And it's not relevant anymore with the merge of otp.
