### ISSUE TITLE
Back in business

### ISSUE THREAD

**Issue by Annwenn** [alco/chatty#7]
Hello :) 
I've been sent by your past self to tell you that there's actually a point in making Chatty a fully OTP application.
Hope you're having a nice week-end =)

**Comment by alco** [comment]
Hey. Thanks for reminding me. It is going to be done this week.

**Comment by Annwenn** [comment]
Glad to know :)

**Comment by alco** [comment]
https://github.com/alco/chatty/pull/8
![It's happening](http://i.imgur.com/7XpJTcZ.gif)
